on: push
name: Publish Website
jobs:
  web-deploy:
    name: Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: pyroll.org

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install APT Packages
      run: sudo apt-get install inkscape

    - name: Install Pipenv
      run: pip install pipenv

    - name: Install Python Environment via Pipenv
      run: pipenv install

    - name: Run Build Tasks
      run: pipenv run tasks

    - name: Build Sphinx Docs
      run: pipenv run sphinx
      continue-on-error: true

    - name: Publish Files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: pyroll.org
        username: githubactions
        password: ${{ secrets.FTP_PASSWORD }}
        local_dir: ./build